# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b972d8b12f3018dfc7fc9060c96271c69dd249ac6e4ee426df265f5b9be1594752371af447abe68f644e7852f83b71efc4c78f8e210270ea4ccfa7a3a0f6ed

test:
  secret_key_base: 4094fe11ef36d8f0194852c9635ef638f2eb1b7dd0baa9c58457a8a7ec16fd3b17df6324bf615e9b63101f778ac634038f7c3bc33b6b409bdbd01d958963b028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
